clarin-eric/switchboard

Makefile, webui/src/components/AlertURLUploadError.jsx, webui/src/components/App.jsx, webui/src/components/DropArea.jsx
fixes https://github.com/clarin-eric/switchboard/issues/6
=> show correct maxsize in UI dialog

README.md
removed the reference to version 1.0.0 
added a section on the Tool registry
added a contact section
=> some small updates

backend/src/main/java/eu/clarin/switchboard/core/DefaultStoragePolicy.java, backend/src/main/java/eu/clarin/switchboard/core/Tool.java, backend/src/test/java/eu/clarin/switchboard/core/DefaultStoragePolicyTest.java, webui/src/components/DropArea.jsx, webui/src/components/MatcherRemote.js, webui/src/components/MimetypeMenu.jsx
fixes #14 
Please note: this fix is dependent on https://github.com/clarin-eric/switchboard-tool-registry/pull/11
=> accept xml in storage, fix missing tool parameters

webui/src/components/ToolList.jsx
=> misc ui issues: #58, #59

webui/src/components/About.jsx, webui/src/components/ForDevelopers.jsx
=> add funding info and add help link to tool registry

backend/pom.xml, webui/package-lock.json, webui/package.json, webui/src/components/Highlighter.jsx, webui/src/components/ToolList.jsx
=> Support markdown (GitHub flavor) in tools description and auth info

webui/src/actions/actions.jsx, webui/src/components/ToolList.jsx
=> render markdown in licence

Changelog.md, INSTALL.md, backend/pom.xml, backend/src/main/java/eu/clarin/switchboard/app/HttpErrorHandler.java, backend/src/main/java/eu/clarin/switchboard/resources/DataResource.java
=> misc fixes in changelog, install and pom

backend/src/main/java/eu/clarin/switchboard/core/LinkMetadata.java, backend/src/main/java/eu/clarin/switchboard/core/MediaLibrary.java, webui/package-lock.json, webui/package.json, webui/src/actions/utils.jsx, webui/src/components/Resource.jsx
There was a bug that manifested when the uploaded resource was just too big.
=> fix for server storage IO error (resource closed too soon)

webui/src/components/About.jsx
=> add SSHOC funding info

backend/src/main/java/eu/clarin/switchboard/core/LinkMetadata.java, backend/src/main/java/eu/clarin/switchboard/resources/InfoResource.java, backend/src/main/resources/iso639-3.tsv, webui/src/actions/actions.jsx, webui/src/actions/toolcall.jsx, webui/src/actions/utils.jsx, webui/src/components/ToolList.jsx
=> Bug fixes (languages in UI, errors while downloading resources)

backend/src/main/java/eu/clarin/switchboard/resources/InfoResource.java, backend/src/main/resources/iso639-3.tsv, webui/package-lock.json, webui/src/actions/actions.jsx, webui/src/actions/toolcall.jsx, webui/src/actions/utils.jsx, webui/src/components/ToolList.jsx
fixes #150 (now in 2.2.x branch)
There is still one high npm vulnerability, which I don't think can be solved easily. We have to migrate to 2.3.0.
=> Bugfixes: missing language selection

backend/src/main/java/eu/clarin/switchboard/resources/DataResource.java, webui/src/actions/toolcall.jsx
=> use user-selected mediatype for file data request header

backend/pom.xml, backend/src/main/java/eu/clarin/switchboard/core/LinkMetadata.java, backend/src/test/java/eu/clarin/switchboard/core/LinkMetadataTest.java
fixes https://github.com/clarin-eric/switchboard/issues/163
=> try to take the filename from url

webui/src/actions/actions.jsx
=> fix multiple resources when they should not

webui/src/actions/toolcall.jsx
=> bug fix: urlencode mediatype parameter

backend/src/main/java/eu/clarin/switchboard/resources/MainResource.java, webui/src/actions/toolcall.jsx, webui/src/components/NavBar.jsx, webui/src/components/ToolList.jsx
The popup looks like in the image below. We should discuss what should happen if the user clicks on the title; right now a new empty browser page is loaded with the switchboard's address. Should it behave like the maximize button?
=> add maximize button for popup

backend/src/main/java/eu/clarin/switchboard/core/FileInfo.java, backend/src/main/java/eu/clarin/switchboard/core/LinkMetadata.java, backend/src/main/java/eu/clarin/switchboard/core/Quirks.java, backend/src/main/java/eu/clarin/switchboard/core/ToolRegistry.java, backend/src/main/java/eu/clarin/switchboard/resources/MainResource.java, backend/src/main/resources/webui/css/switchboard.css, backend/src/main/resources/webui/popup/switchboardpopup.js, webui/src/actions/actions.jsx, webui/src/actions/utils.jsx, webui/src/components/Resource.jsx, webui/src/components/ToolList.jsx
Changes:
- the popup is now movable and has a "maximize" and a "close" button on it. 
- adds "lookup tools" mode: if the data content is text up to 3 words, only the "lookup tools" are displayed.
- moved special cases of data massaging based on origin and hostnames in a dedicated "Quirks" file (as other projects have, e.g. https://github.com/WebKit/WebKit/blob/main/Source/WebCore/page/Quirks.cpp)
=> "Lookup tools" mode, popup maximize and close buttons

backend/src/main/java/eu/clarin/switchboard/tool/Tool.java
see https://github.com/clarin-eric/switchboard-tool-registry/pull/107 for some information on the field
=> add integrationType field in json format

backend/src/main/java/eu/clarin/switchboard/core/DataStore.java, backend/src/main/java/eu/clarin/switchboard/core/MediaLibrary.java, backend/src/main/java/eu/clarin/switchboard/resources/DataResource.java, backend/src/main/resources/webui/css/switchboard.css, backend/src/test/java/eu/clarin/switchboard/core/DataStoreTest.java, webui/src/actions/actions.jsx, webui/src/components/Main.jsx, webui/src/components/Resource.jsx, webui/src/constants.jsx, webui/src/containers/MainContainer.jsx, webui/src/index.jsx
When the resource is a selection the content is now editable.
=> make selection resources editable

webui/src/actions/actions.jsx, webui/src/components/Resource.jsx
=> disable remove for unique resource, blur selection editing on enter

backend/pom.xml, backend/src/main/java/eu/clarin/switchboard/resources/DataResource.java, backend/src/test/java/eu/clarin/switchboard/core/DataStoreTest.java, backend/src/test/java/eu/clarin/switchboard/core/MediaLibraryTest.java, backend/src/test/java/eu/clarin/switchboard/resources/DataResourceTest.java
fixes https://github.com/clarin-eric/switchboard/issues/64
=> Set content-encoding for text utf8 files

backend/src/main/java/eu/clarin/switchboard/resources/DataResource.java, webui/src/components/Main.jsx
fixes #210 
Unfortunately a new release is necessary.
=> bug fix: allow old-style repository calls

backend/src/main/java/eu/clarin/switchboard/app/SwitchboardApp.java, backend/src/main/java/eu/clarin/switchboard/app/config/SwitchboardConfig.java, backend/src/main/java/eu/clarin/switchboard/resources/DataResource.java, backend/src/main/java/eu/clarin/switchboard/resources/InfoResource.java, backend/src/main/resources/webui/popup/switchboardpopup.js
Paired with the documentation update in this PR: https://github.com/clarin-eric/switchboard-doc/pull/14. The documentation for the popup title can be found here: https://github.com/clarin-eric/switchboard-doc/pull/14/files#diff-dc84ddb63a6d79e430c477782f39cb5313256b5b37e72d6193efc5ba3fd2415bR72
=> Allow repositories to set popup title

.gitmodules, Dockerfile, backend/pom.xml, backend/src/main/java/eu/clarin/switchboard/app/SwitchboardApp.java, backend/src/main/java/eu/clarin/switchboard/core/FileInfo.java, backend/src/main/java/eu/clarin/switchboard/core/MediaLibrary.java, backend/src/main/java/eu/clarin/switchboard/core/ToolRegistry.java, backend/src/main/java/eu/clarin/switchboard/core/xc/ConverterException.java, backend/src/main/java/eu/clarin/switchboard/core/xc/SwitchboardExceptionMapper.java, backend/src/main/java/eu/clarin/switchboard/resources/DataResource.java, backend/src/main/java/eu/clarin/switchboard/resources/ToolsResource.java, backend/src/main/java/eu/clarin/switchboard/tool/Input.java, backend/src/main/java/eu/clarin/switchboard/tool/Tool.java, backend/src/main/resources/webui/css/switchboard.css, backend/src/test/java/eu/clarin/switchboard/core/MediaLibraryTest.java, backend/src/test/java/eu/clarin/switchboard/core/ToolRegistryTest.java, backend/src/test/java/eu/clarin/switchboard/resources/DataResourceTest.java, backend/src/test/resources/registry/Variadic.json, webui/package-lock.json, webui/src/actions/actions.jsx, webui/src/actions/reducers.jsx, webui/src/actions/toolcall.jsx, webui/src/actions/utils.jsx, webui/src/components/Main.jsx, webui/src/components/Resource.jsx, webui/src/components/ToolList.jsx, webui/src/constants.jsx, webui/src/containers/MainContainer.jsx, webui/src/index.jsx
=> Simple docs to text conversions

backend/src/main/java/eu/clarin/switchboard/resources/DataResource.java, backend/src/test/java/eu/clarin/switchboard/resources/DataResourceTest.java, webui/src/actions/actions.jsx, webui/src/components/Main.jsx, webui/src/components/Resource.jsx, webui/src/constants.jsx, webui/src/containers/MainContainer.jsx, webui/src/index.jsx
=> Add "show more content" button

backend/src/main/java/eu/clarin/switchboard/resources/IndexView.java, backend/src/main/java/eu/clarin/switchboard/resources/MainResource.java, backend/src/main/resources/webui/popup/switchboardpopup.js, webui/src/index.jsx
This is useful in the case of multiple resources, all matched together against tools. Fixes #154
=> Support repos sending multiple urls at the same time

backend/src/main/java/eu/clarin/switchboard/core/LinkMetadata.java
=> fix resource leak when http calls return 40x

backend/config.yaml, backend/src/main/java/eu/clarin/switchboard/app/SwitchboardApp.java, backend/src/main/java/eu/clarin/switchboard/app/config/UrlResolverConfig.java, backend/src/main/java/eu/clarin/switchboard/core/MediaLibrary.java, backend/src/main/java/eu/clarin/switchboard/core/ToolRegistry.java, backend/src/main/java/eu/clarin/switchboard/resources/ToolsResource.java, backend/src/main/java/eu/clarin/switchboard/resources/UrlMatchResource.java, backend/src/main/resources/webui/popup/switchboardpopup.js, backend/src/test/java/eu/clarin/switchboard/core/MediaLibraryTest.java, backend/src/test/java/eu/clarin/switchboard/resources/DataResourceTest.java
Docs for this feature are now in this other PR: https://github.com/clarin-eric/switchboard-doc/pull/20
=> Support preflight api

.github/workflows/main.yml
=> Update to SauceConnect 5

backend/pom.xml
- tika to 3.0.0
- bcprov-jdk18on to 1.79
- junit-jupiter-api to 5.11.3
- maven-release-plugin to 3.1.1
=> Update maven dependencies
